dist: trusty

sudo: required

install:
    # Overriding the default `install` stage:
    - awk --version

script:
    - ./tests/runtests.sh

after_failure:
  - for f in tests/*out; do head ${f%.out}.ok; head $f; done
